name: Version Bump

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Type of version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install bump2version
        run: npm install -g bump2version

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Bump version
        run: |
          if [ "${{ github.event.inputs.bump_type }}" == "major" ]; then
            bump2version major
          elif [ "${{ github.event.inputs.bump_type }}" == "minor" ]; then
            bump2version minor
          else
            bump2version patch
          fi

      - name: Push changes
        run: |
          git push --follow-tags

      - name: Create tag
        run: |
          # Get the new version
          NEW_VERSION=$(grep -o 'current_version = .*' .bumpversion.cfg | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
          git tag "v${NEW_VERSION}"

      - name: Push tag
        run: |
          git push origin "v$(grep -o 'current_version = .*' .bumpversion.cfg | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')"